/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gov_llnl_lc_infiniband_opensm_plugin_OsmNativeInterface */

#ifndef _Included_gov_llnl_lc_infiniband_opensm_plugin_OsmNativeInterface
#define _Included_gov_llnl_lc_infiniband_opensm_plugin_OsmNativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gov_llnl_lc_infiniband_opensm_plugin_OsmNativeInterface
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_llnl_lc_infiniband_opensm_plugin_OsmNativeInterface_getVersion
  (JNIEnv *, jobject);

/*
 * Class:     gov_llnl_lc_infiniband_opensm_plugin_OsmNativeInterface
 * Method:    wait_for_event
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gov_llnl_lc_infiniband_opensm_plugin_OsmNativeInterface_wait_1for_1event
  (JNIEnv *, jobject, jint);

/*
 * Class:     gov_llnl_lc_infiniband_opensm_plugin_OsmNativeInterface
 * Method:    getOsmNodes
 * Signature: ()Lgov/llnl/lc/infiniband/opensm/plugin/data/OSM_Nodes;
 */
JNIEXPORT jobject JNICALL Java_gov_llnl_lc_infiniband_opensm_plugin_OsmNativeInterface_getOsmNodes
  (JNIEnv *, jobject);

/*
 * Class:     gov_llnl_lc_infiniband_opensm_plugin_OsmNativeInterface
 * Method:    getOsmPorts
 * Signature: ()Lgov/llnl/lc/infiniband/opensm/plugin/data/OSM_Ports;
 */
JNIEXPORT jobject JNICALL Java_gov_llnl_lc_infiniband_opensm_plugin_OsmNativeInterface_getOsmPorts
  (JNIEnv *, jobject);

/*
 * Class:     gov_llnl_lc_infiniband_opensm_plugin_OsmNativeInterface
 * Method:    getOsmStats
 * Signature: ()Lgov/llnl/lc/infiniband/opensm/plugin/data/OSM_Stats;
 */
JNIEXPORT jobject JNICALL Java_gov_llnl_lc_infiniband_opensm_plugin_OsmNativeInterface_getOsmStats
  (JNIEnv *, jobject);

/*
 * Class:     gov_llnl_lc_infiniband_opensm_plugin_OsmNativeInterface
 * Method:    getOsmSysInfo
 * Signature: ()Lgov/llnl/lc/infiniband/opensm/plugin/data/OSM_SysInfo;
 */
JNIEXPORT jobject JNICALL Java_gov_llnl_lc_infiniband_opensm_plugin_OsmNativeInterface_getOsmSysInfo
  (JNIEnv *, jobject);

/*
 * Class:     gov_llnl_lc_infiniband_opensm_plugin_OsmNativeInterface
 * Method:    getPluginInfo
 * Signature: ()Lgov/llnl/lc/infiniband/opensm/plugin/data/OSM_PluginInfo;
 */
JNIEXPORT jobject JNICALL Java_gov_llnl_lc_infiniband_opensm_plugin_OsmNativeInterface_getPluginInfo
  (JNIEnv *, jobject);

/*
 * Class:     gov_llnl_lc_infiniband_opensm_plugin_OsmNativeInterface
 * Method:    getOsmSubnet
 * Signature: ()Lgov/llnl/lc/infiniband/opensm/plugin/data/OSM_Subnet;
 */
JNIEXPORT jobject JNICALL Java_gov_llnl_lc_infiniband_opensm_plugin_OsmNativeInterface_getOsmSubnet
  (JNIEnv *, jobject);

/*
 * Class:     gov_llnl_lc_infiniband_opensm_plugin_OsmNativeInterface
 * Method:    invokeCommand
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_llnl_lc_infiniband_opensm_plugin_OsmNativeInterface_invokeCommand
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
